chore: change name to reflect branding
thepurplebubble/site pull request #19
Opened 2023-12-12 23:56 UTC by kcoderhtml

# Name Change
## Description:

Change the name of the org across the site and add a proper README

2023-12-12 23:57 UTC, jdogcoder commented
Looks good so far, lmk when it's ready for me!

2023-12-13 00:01 UTC, kcoderhtml commented
All good on my side!

2023-12-13 00:03 UTC, jdogcoder requested changes

2023-12-13 00:03 UTC, jdogcoder commented on README.md
> +# Purple Bubble Website
This should be `Purple Bubble's Website` I think :)

2023-12-13 00:03 UTC, jdogcoder commented
Very minor change requested @kcoderhtml

2023-12-13 00:08 UTC, jdogcoder approved these changes

2023-12-13 00:08 UTC, merged