Add email form
thepurplebubble/site pull request #21
Opened 2023-12-14 16:01 UTC by kcoderhtml

# Add email form
## Description:

Add the form and a Netlify function to proxy the request.

## Related Issue:
Closes #18

2023-12-18 01:23 UTC, jdogcoder commented on public/bg.png
What's going on with this change @kcoderhtml?

![CleanShot 2023-12-17 at 20 22 44@2x](https://github.com/thepurplebubble/site/assets/65788728/c221b0a7-02ba-4f52-89a1-9d9573748505)

2023-12-18 01:24 UTC, kcoderhtml commented on public/bg.png
@CaenJones wanted to change it so that it wasn't overlapping and looking so much like an image.

2023-12-18 01:25 UTC, kcoderhtml commented on public/bg.png
we may want to have @polypixeldev look at it and see if he has any thoughts.

2023-12-18 01:25 UTC, jdogcoder commented on public/bg.png
I do like them both.

2023-12-18 01:26 UTC, jdogcoder commented on public/bg.png
Let's get @polypixeldev on this tho :)

2023-12-18 03:05 UTC, polypixeldev commented
goofy bug - bg image doesn't show by default but it does when i open devtools? firefox/linux
![image](https://github.com/thepurplebubble/site/assets/79737178/6feac31d-ea32-463a-88d4-f3086bf65a06)

2023-12-18 03:06 UTC, polypixeldev commented on public/bg.png
looks good to me!

2023-12-18 17:12 UTC, jdogcoder approved these changes
LGTM

2023-12-18 17:13 UTC, jdogcoder commented
Oh wait

2023-12-18 17:13 UTC, jdogcoder requested changes
can we fix the above first

2023-12-18 17:57 UTC, kcoderhtml commented
@polypixeldev are you having the bg issue on the main site? https://purplebubble.org

2023-12-18 18:00 UTC, kcoderhtml commented
I just tested firefox, chrome, and safari on mac and they all worked fine.

2023-12-18 18:05 UTC, kcoderhtml commented
On a pixel 4 with chrome, it looks like below, which is a problem.  
![image](https://github.com/thepurplebubble/site/assets/92754843/20928f9c-0d07-4828-bef6-ab8eb549f46d)

2023-12-18 21:58 UTC, polypixeldev commented
> @polypixeldev are you having the bg issue on the main site? https://purplebubble.org

I am getting the same issue on main site

2023-12-18 23:03 UTC, kcoderhtml commented
weird; maybe its a config issue on your end? have you tried a private session or new profile?

2023-12-19 01:49 UTC, jdogcoder approved these changes

2023-12-19 01:52 UTC, merged